# Generated by Django 2.2 on 2021-02-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(max_length=200, verbose_name='نام استان')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(max_length=200, verbose_name='شهر')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_management.State', verbose_name='استان')),
            ],
        ),
    ]
