# Generated by Django 2.2 on 2021-01-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_management', '0002_post_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_verify',
            field=models.BooleanField(default=True, verbose_name='تایید شده؟'),
        ),
    ]
