# Generated by Django 2.2 on 2021-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_management', '0003_auto_20210127_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/posts_image', verbose_name='عکس پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/posts_image', verbose_name='عکس پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
